// <auto-generated />
namespace BookStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_book_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_book_model));
        
        string IMigrationMetadata.Id
        {
            get { return "202101081404518_Update_book_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
